### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by stre1026** [firstone/holidays-poly#3]
Hello, I'm having an issue getting this to start on my UDI Polisy. It's telling me the dateparser module is not found. I've tried to install it using sudo pip install dateparser and it fails installing the regex module. Have you installed this on a UDI Polisy with success?

**Comment by firstone** [comment]
Can you send an error? Also, have you tried with python3 -m pip? I've just installed it a few days ago and it seemed fine.

**Comment by stre1026** [comment]
Here it is:


Traceback (most recent call last):
  File "/usr/local/lib/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/local/lib/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/var/polyglot/nodeservers/Holidays/tests/test_rules.py", line 7, in <module>
    from holidays_server import Rule
  File "/var/polyglot/nodeservers/Holidays/holidays_server.py", line 5, in <module>
    import dateparser
ModuleNotFoundError: No module named 'dateparser'


________________________________

**Comment by firstone** [comment]
No, not node server log. pip install log. or pip3 install or python3 -m pip install

**Comment by stre1026** [comment]
[admin@polisy ~]$ sudo python3 -m pip install dateparser
Collecting dateparser
  Using cached dateparser-1.0.0-py2.py3-none-any.whl (279 kB)
Collecting regex!=2019.02.19
  Using cached regex-2020.11.13.tar.gz (694 kB)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.7/site-packages (from dateparser) (2.8.1)
Requirement already satisfied: tzlocal in /usr/local/lib/python3.7/site-packages (from dateparser) (2.1)
Requirement already satisfied: pytz in /usr/local/lib/python3.7/site-packages (from dateparser) (2021.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/site-packages (from python-dateutil->dateparser) (1.15.0)
Building wheels for collected packages: regex
  Building wheel for regex (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-86vy7xl6/regex/setup.py'"'"'; __file__='"'"'/tmp/pip-install-86vy7xl6/regex/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-akp7yq96
       cwd: /tmp/pip-install-86vy7xl6/regex/
  Complete output (17 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.freebsd-12.2-RELEASE-p4-amd64-3.7
  creating build/lib.freebsd-12.2-RELEASE-p4-amd64-3.7/regex
  copying regex_3/__init__.py -> build/lib.freebsd-12.2-RELEASE-p4-amd64-3.7/regex
  copying regex_3/regex.py -> build/lib.freebsd-12.2-RELEASE-p4-amd64-3.7/regex
  copying regex_3/_regex_core.py -> build/lib.freebsd-12.2-RELEASE-p4-amd64-3.7/regex
  copying regex_3/test_regex.py -> build/lib.freebsd-12.2-RELEASE-p4-amd64-3.7/regex
  running build_ext
  building 'regex._regex' extension
  creating build/temp.freebsd-12.2-RELEASE-p4-amd64-3.7
  creating build/temp.freebsd-12.2-RELEASE-p4-amd64-3.7/regex_3
  cc -pthread -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -fPIC -I/usr/local/include/python3.7m -c regex_3/_regex.c -o build/temp.freebsd-12.2-RELEASE-p4-amd64-3.7/regex_3/_regex.o
  unable to execute 'cc': No such file or directory
  error: command 'cc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for regex
  Running setup.py clean for regex
Failed to build regex
Installing collected packages: regex, dateparser
    Running setup.py install for regex ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-86vy7xl6/regex/setup.py'"'"'; __file__='"'"'/tmp/pip-install-86vy7xl6/regex/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-w3zzbvp5/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7m/regex
         cwd: /tmp/pip-install-86vy7xl6/regex/
    Complete output (17 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.freebsd-12.2-RELEASE-p4-amd64-3.7
    creating build/lib.freebsd-12.2-RELEASE-p4-amd64-3.7/regex
    copying regex_3/__init__.py -> build/lib.freebsd-12.2-RELEASE-p4-amd64-3.7/regex
    copying regex_3/regex.py -> build/lib.freebsd-12.2-RELEASE-p4-amd64-3.7/regex
    copying regex_3/_regex_core.py -> build/lib.freebsd-12.2-RELEASE-p4-amd64-3.7/regex
    copying regex_3/test_regex.py -> build/lib.freebsd-12.2-RELEASE-p4-amd64-3.7/regex
    running build_ext
    building 'regex._regex' extension
    creating build/temp.freebsd-12.2-RELEASE-p4-amd64-3.7
    creating build/temp.freebsd-12.2-RELEASE-p4-amd64-3.7/regex_3
    cc -pthread -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -O2 -pipe -fstack-protector-strong -fno-strict-aliasing -fPIC -I/usr/local/include/python3.7m -c regex_3/_regex.c -o build/temp.freebsd-12.2-RELEASE-p4-amd64-3.7/regex_3/_regex.o
    unable to execute 'cc': No such file or directory
    error: command 'cc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-86vy7xl6/regex/setup.py'"'"'; __file__='"'"'/tmp/pip-install-86vy7xl6/regex/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-w3zzbvp5/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7m/regex Check the logs for full command output.

**Comment by firstone** [comment]
Yes, it makes sense. There's no cc compiler on polisy but I think we've specifically included that package. I do not recall for sure. I'll search for it and will let you know. It's possible you need to update something.

**Comment by firstone** [comment]
Try this:

sudo pkg install py37-dateparser

**Comment by stre1026** [comment]
So that install was successful , but now the node server starts and stops. It won't stay running and there is nothing that shows up in the logs.

________________________________

**Comment by stre1026** [comment]
I just uninstalled Holidays from the store and then reinstalled it and now it seems to be working!
________________________________

**Comment by firstone** [comment]
The fact that you don't have that module to start with implies you have an older version of package list on polisy. You should probably search how to update it. But, if it works as-is, I guess you don't have to touch it.
